services:
  backend:
    build: "./backend"
    ports:
      - "5001:5001"
    env_file:
      - "./backend/.env"
  frontend:
    build: "./frontend_web"
    ports:
      - "3000:3000"
    env_file:
      - "./frontend_web/.env"
    depends_on:
      - "backend"
